### ISSUE TITLE
tutorial feedback

### ISSUE THREAD

**Issue by canavandl** [StevenCHowell/pyohio_2017_bokeh#1]
All-in-all, I think it's pretty good.

I'd mention that you're covering the bokeh.plotting API specifically and there exists a lower-level bokeh.models API.

nb 0
* specify Bokeh should go from "BokehJS loading..." to "BokehJS 0.12.6 successfully loaded."
* re: browser recommendations, there previously was a bug Safari that caused websockets to not work. It may have been resolved, but it users haven't updated they'd maybe hit it. You don't have to mention it, but if somebody is having problems w/ Safari, maybe suggest changing browsers.
nb 1
* I like the inline resources workaround suggestion
* "with the added kwarg linewidth" -> should be line_width
nb 3
* My browser window bogs down when running the whole notebook via Run All. It may be worth considering reducing the data size or manually GC-ing some DataSources when you're done with them.

Let me know if you need help putting together a server example. Otherwise, I'm excited to watch the tutorial on YT when it's uploaded.

**Comment by StevenCHowell** [comment]
@canavandl Thank you for looking over this.  

For the server example, I never figured out where I was going wrong.  I may get to look at it tomorrow while traveling but I am not sure.  If you have time, it would be great if you could have a look at what is now called `./material/04-gaussian-server.py`.  

I decided I liked the notebook from the bokeh-notebooks repo for teaching about using `bokeh server`.  I would still like to get my demo working as an illustration but we'll see.
